### ISSUE TITLE
I am getting Bad authnetication error

### ISSUE THREAD

**Issue by d78ui98** [NoMore201/googleplay-api#140]
[ERROR] Bad authentication, login or password incorrect ('server says: BadAuthentication')

**Comment by ouaguid** [comment]
The email address used (or its password) is wrong, check it again by trying to connect to your Gmail account (via a browser).

**Comment by falcon4ever** [comment]
I'm getting the same error as @d78ui98 when providing the correct email/password (verified on https://accounts.google.com/ )

**Comment by d78ui98** [comment]
Hello ouaguid. Thanks for the reply.
The email and password used were right. Was still not able to connect. 
But now I am able to fix this issue.
Thank you anyway :)

**Comment by nosnikta10** [comment]
I am also getting a "BadAuthentication" response from the server. I have verified the password and email is correct and attempted to unlock the account here "https://accounts.google.com/b/0/DisplayUnlockCaptcha". I have also tried multiple different accounts. @d78ui98 How did you end up getting auth working again?

**Comment by nosnikta10** [comment]
Turns out to be the version of requests not playing nice with the lib. I downgraded from requests version 2.25.1 to 2.20.0 and now I can sign in. I hope that helps someone else having the same issue.

**Comment by ryu-s-r** [comment]
I havn't tracked all the packet but the [Raccoon ](https://github.com/onyxbits/Raccoon)is working well.
I am using the GSFID and token from it.

**Comment by ryu-s-r** [comment]
I found the problem. it was proxy in my case.

**Comment by elbandi** [comment]
I found the a possible explanation: the auth header different for different auth type:
if you use token, the auth header sould be in [googleplay.py#L144 ](https://github.com/NoMore201/googleplay-api/blob/master/gpapi/googleplay.py#L144):
`headers["Authorization"] = "Bearer %s" % self.authSubToken`

But if you use username/password (i use "app password"), the auth header works this:
`            headers["Authorization"] = "GoogleLogin auth=%s" % self.authSubToken`

**Comment by Jarijaas** [comment]
> Turns out to be the version of requests not playing nice with the lib. I downgraded from requests version 2.25.1 to 2.20.0 and now I can sign in. I hope that helps someone else having the same issue.


The reason for why you have to do this is that the Auth API does TLS fingerprinting, so the client has to have a specific TLS signature otherwise the server rejects the requests.  

> I found the problem. it was proxy in my case.

For this same reason, the auth API cannot be used with most proxies because the proxy messes with the TLS fingerprint. I did some experimentation with the fingerprinting and found a valid fingerprint that at least for me has worked reliably: 
<https://github.com/Jarijaas/go-googleplay/tree/02045ae52a0a2f89f909d2492a53f3961c51bfaf/pkg/auth/utils.go#L95-L138>

**Comment by gentoolinux** [comment]
Here is a quick and dirty patch for the Bad Authentication issue: https://github.com/gentoolinux/googleplay-api/commit/6e4c7a47b59f2a1a512b05380127f87369e308ff
This solves the issue for me but some advanced programmer should check this before merging it.
My patch is inspired by https://github.com/simon-weber/gpsoauth/commit/6a52a38b35db9b0732d4cec04f734963ca1dc578

**Comment by ahm750** [comment]
> I havn't tracked all the packet but the [Raccoon ](https://github.com/onyxbits/Raccoon)is working well.
> I am using the GSFID and token from it.

Racoon also returned "Bad authentication" error

**Comment by martinwang2002** [comment]
> Turns out to be the version of requests not playing nice with the lib. I downgraded from requests version 2.25.1 to 2.20.0 and now I can sign in. I hope that helps someone else having the same issue.

I downgraded `urllib3<1.26.0` (which is same as downgrading requests) and there is no more BadAuthentication. I think there are some ssl errors causing this.

If you stick to `urllib3>1.26.0`, you can try https://github.com/NoMore201/googleplay-api/pull/145. I think it is already fixed.

**Comment by 89z** [comment]
As was previously mentioned [1], the problem is that newer versions of `urllib` have a different TLS signature from older versions. Downgrading is a temporary solution, but a better option is to manually set a known good TLS fingerprint. This is done with PR 145.

For another approach, I captured the TLS fingerprints of Android API 24-32, which are whitelisted by Google [2].

1. https://github.com/NoMore201/googleplay-api/issues/140#issuecomment-869165778
2. https://github.com/89z/format/blob/v1.22.8/crypto/crypto.go#L136-L156

**Comment by NachumOlman** [comment]
started getting this issue again lately while trying to login.
2fa with Playstore app password.
tried solutions in linked issues and PRs, the issue persist
tried with/without vpn, the issue persist

did anybody successfully login in the last couple of days?

**Comment by besendorf** [comment]
> started getting this issue again lately while trying to login. 2fa with Playstore app password. tried solutions in linked issues and PRs, the issue persist tried with/without vpn, the issue persist
> 
> did anybody successfully login in the last couple of days?

My fork works for me. I also uploaded it to pypi.
https://github.com/besendorf/googleplay-api
