### ISSUE TITLE
Token expires after a short time

### ISSUE THREAD

**Issue by NoMore201** [NoMore201/googleplay-api#18]
After some time of "inactivity" during a session, google starts answering with empty responses like this:
```
>>> server.bulkDetails(['org.mozilla.focus'])
[{'docId': '', 'title': '', 'author': '', 'offer': [], 'images': [], 'versionCode': 0, 'installationSize': 0, 'numDownloads': '', 'uploadDate': '', 'files': [], 'unstable': False, 'containsAds': '', 'aggregateRating': {'type': 0, 'starRating': 0.0, 'ratingsCount': 0, 'oneStarRatings': 0, 'twoStarRatings': 0, 'threeStarRatings': 0, 'fourStarRatings': 0, 'fiveStarRatings': 0, 'commentCount': 0}, 'dependencies': [], 'category': {'appType': '', 'appCategory': ''}, 'detailsUrl': ''}]
>>> server.search('termux', 1)
Unexpected behaviour
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nomore/workspace/nogoogle/googleplay-api/gpapi/googleplay.py", line 292, in search
    cluster = response.payload.listResponse.cluster[0]
IndexError: list index out of range
```

If you login again, API starts working again until another 5 minutes of inactivity. It seems like the token expires after a short time, but this is strange since auth tokens were thought to be valid for months. I'm quite sure it doesn't depend on gpapi code, but it is a google break.

Steps to reproduce issue:

- Open a python interactive shell
- Initialize object and login
```
from gpapi.googleplay import GooglePlayAPI
server = GooglePlayAPI()
server.login(EMAIL,  PASSWD, None, None)
```
- Start playing around with the api, it should work without problems
- Leave the shell open for some minutes without interaction (in my case 5 minutes was enough)
- Try to execute another query

Let me know if you can reproduce this behaviour

**Comment by GoyfAscetic** [comment]
I can reproduce this behavior

**Comment by matlink** [comment]
Same here. I've written a little patch to get a new token in `gplaycli`.

**Comment by NoMore201** [comment]
Same, I added some code to [playmaker](https://github.com/NoMore201/playmaker) to fetch a new token in case it's not valid anymore. I wonder if other projects are having the same issue.

**Comment by dizzy666** [comment]
I can reproduce this problem with latest playmaker. After a few minutes the logs get flooded

`11:38.306581787Z Session tokens expired, re-login needed
11:38.834709205Z authSubToken: ...
11:39.223269093Z Session tokens expired, re-login needed
11:39.802276499Z authSubToken: ...
...
12:00.708673152Z Session tokens expired, re-login needed
12:01.038289746Z authSubToken: ...
12:01.296437585Z Session tokens expired, re-login needed
12:01.525255998Z Wrong credentials: 'server says: ServerError'
12:01.796446797Z Session tokens expired, re-login needed
12:02.003540987Z Wrong credentials: 'server says: ServerError'
...`

**Comment by NoMore201** [comment]
@dizzy666 are you sure you're using the latest version? I fixed those problems some days ago, now it's working as intended (at least for me and a bunch of other people). I just uploaded the latest version on Docker Hub, be sure to `docker pull nomore201/playmaker` before running it.

**Comment by dizzy666** [comment]
@NoMore201 same error.

**Comment by dizzy666** [comment]
I have tried GooglePlayAPI in a Python shell.
`
server.login(None, None, gsfId, authSubToken)
`
and search works fine but after a few minutes search return a error (expired toke).
I try server.login again but it fails.
```
>>> server.search('telegram', 1, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 268, in search
    raise LoginError('Unexpected behaviour, probably expired '
gpapi.googleplay.LoginError: 'Unexpected behaviour, probably expired token'
>>> server.login(None, None, gsfId, authSubToken)
authSubToken: ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 185, in login
    self.search('firefox', 1, None)
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 268, in search
    raise LoginError('Unexpected behaviour, probably expired '
gpapi.googleplay.LoginError: 'Unexpected behaviour, probably expired token'
>>> server.search('telegram', 1, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gpapi/googleplay.py", line 268, in search
    raise LoginError('Unexpected behaviour, probably expired '
gpapi.googleplay.LoginError: 'Unexpected behaviour, probably expired token'
```

**Comment by NoMore201** [comment]
Here it is, once again @yeriomin has the answer to the problem. It seems related to the token TTL parameter, and a second auth request is needed.

https://github.com/yeriomin/play-store-api/commit/6544937ac2b9c513044d2b510b835c6e7bc2b8da

**Comment by dizzy666** [comment]
I have tried latest git source. The problem still exist.

```
2017-11-03T16:30:34.668296905Z Session tokens expired, re-login needed
2017-11-03T16:30:35.132646855Z Master token: ....
2017-11-03T16:30:35.315442227Z authSubToken: ...
2017-11-03T16:30:35.644395731Z Session tokens expired, re-login needed
```
And the logs get flooded.
